interface Technology {
    id: string,
    desc: string
}
export interface Movie {
    id: string,
    title: string,
    title_episode: string,
    title_uri: string,
    title_original: string,
    description: string,
    description_large: string,
    image_large: string,
    image_medium: string,
    image_small: string,
    image_still: string,
    image_background: string,
    url_imagen_t1: string,
    url_imagen_t2: string,
    image_base_horizontal: string,
    image_base_vertical: string,
    image_base_square: string,
    image_clean_horizontal: string,
    image_clean_vertical: string,
    image_clean_square: string,
    image_sprites: string,
    image_frames: string,
    duration: string,
    date: string,
    year: string,
    preview: string,
    season_number: string,
    episode_number: string,
    format_types: string,
    live_enabled: string,
    live_type: string,
    live_ref: string,
    channel_number: string,
    timeshift: string,
    votes_average: number,
    rating_code: string,
    proveedor_name: string,
    proveedor_code: string,
    encoder_tecnology: Technology,
    recorder_technology: Technology,
    resource_name: string
}